name: Build Model

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Setup Git LFS
      run: |
        git lfs install
        echo "*.weights filter=lfs diff=lfs merge=lfs -text" > .gitattributes
        echo "*.gguf filter=lfs diff=lfs merge=lfs -text" > .gitattributes

    - name: Install cog
      run: sh <(curl -fsSL https://raw.githubusercontent.com/fortunestoldco/cog-gguf/refs/heads/master/autocog.sh?token=GHSAT0AAAAAAC6QCSZT32APVG4EHMGVMDAGZ5VDB3A)

    - name: Run script to download weights
      run: cog run script/download_weights

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: weights/*
        name: Model Weights ${{ github.sha }}
        tag_name: weights-${{ github.sha }}
        body: |
          Model weights generated at ${{ github.event.head_commit.timestamp }}
          Commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cleanup weights folder
      if: always()
      run: rm -rf weights/
